#!/usr/bin/env bash

set -euo pipefail

# based on https://github.com/babashka/babashka/blob/master/script/install-graalvm

INSTALL_DIR="${1:-$HOME}"

GRAALVM_VERSION="${GRAALVM_VERSION:-22.1.0}"
JAVA_VERSION="${JAVA_VERSION:-17}"

GRAALVM_PLATFORM="$CIRRUS_OS"

case "${CIRRUS_ARCH:-}" in
	arm64)
		GRAALVM_ARCH="aarch64"
		;;
	*)
		GRAALVM_ARCH="amd64"
		;;
esac

GRAALVM_FILENAME="graalvm-ce-java$JAVA_VERSION-$GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION.tar.gz"

pushd "$INSTALL_DIR" >/dev/null

if ! [ -d "graalvm-ce-java$JAVA_VERSION-$GRAALVM_VERSION" ]; then
	echo "Downloading GraalVM $GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION to '$PWD'..."
	curl -O -sL "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/$GRAALVM_FILENAME"
	tar xzf "$GRAALVM_FILENAME"
	ls -lah
fi

export GRAALVM_HOME="$INSTALL_DIR/graalvm-ce-java$JAVA_VERSION-$GRAALVM_VERSION/Contents/Home"

ls -lah "$GRAALVM_HOME"

if ! [ -e "$GRAALVM_HOME/bin/native-image" ]; then
  echo "Installing native-image command..."
  "$GRAALVM_HOME"/bin/gu install native-image
fi

popd >/dev/null
