name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: 22.1.0
          java: java17
      - name: Setup native-image
        run: gu install native-image
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: 1.11.1.1113
      - name: Build binary
        run: clojure -T:build native-image